baseURL = "https://www.jespersopskrifter.dk/"

languageCode = "da-dk"
title = "Jespers Opskrifter"
theme = "one"
googleAnalytics = "UA-127034730-1"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"
enableRobotsTXT = true

[params]
navigation = ["About.md", "links.md", "Glutenfriol.md"]
style = ""
